module.exports = [
  {
      "title": "FerroTime: Electromagnetic Timepiece",
      "description": "A proof-of-concept project to build a captivating clock using electromagnets to display the time with iron filings, blending art and function",
      "creator": "The Timekeepers with Sayan, Shilpi, Mohit",
      "contact": "https://yudocaa.in",
  },
  {
      "title": "Wireless Pirateship",
      "description": "Remotely hand gesture controlled and navigated boat.",
      "creator": "Nikhil, Avjit Singh and Rohit",
      "contact": "",
  },
  {
      "title": "Experiments with Sun Printing",
      "description": "Use the cyanotype printing process to create prints using objects around us",
      "creator": "Arun & Team",
      "contact": "",
  },
  {
      "title": "Loom Bands workshop",
      "description": "",
      "creator": "Ovi & Eva",
      "contact": "",
  },
  {
      "title": "PYSSLA beads",
      "description": "",
      "creator": "Eva",
      "contact": "",
  },
  {
      "title": "Coupled Harmonic Oscillator",
      "description": "",
      "creator": "Jithin BP, Ishaan Singh and Praveen Patil",
      "contact": "/writeups/harmonicoscillator",
  },
  {
      "title": "High voltage source and infusion pump",
      "description": "",
      "creator": "Praveen & Team",
      "contact": "",
  },
  {
      "title": "Plasma vortex",
      "description": "",
      "creator": "Prathmesh & Team",
      "contact": "",
  },
  {
      "title": "Health Vigilance App",
      "description": "Built for patients and elders to raise an alert by monitoring heart rate using bangle JS",
      "creator": "Shabnam, Farhaan, Shekhar",
      "contact": "",
  },
  {
      "title": "Night driving High Beam visibility improvement",
      "description": "Nigh vision driving improvement system using webcam and LCD screen to help drivers avoid bright light during driving",
      "creator": "Anant, Pawman, Mahadev",
      "contact": "",
  },
  {
      "title": "Al resume search model",
      "description": "Based on distilled bert which is a language transformer and GPT 4",
      "creator": "Shreyas",
      "contact": "",
  },
  {
      "title": "Triboelectric Generator",
      "description": "A simple device made from off-the-shelf materials (e.g.,PET plastic and Aluminum foil) for converting low frequency waste random mechanical energy into electricity. Cspark's SEElab3.0 was used as the oscilloscope for measurements (Courtesy of Dr. Jithin)",
      "creator": "Ramakrishna Podila and Team",
      "contact": "",
  },
  {
      "title": "Fractal Chair",
      "description": "Fractal based cushioning of chair based on body shape",
      "creator": "Ishaan Singh and Goutam Samant",
      "contact": "",
  },
  {
      "title": "Bernoulli's effect",
      "description": "",
      "creator": "Atharv inamdar",
      "contact": "",
  },
  {
      "title": "Anamorphic art",
      "description": "",
      "creator": "Minal Patil and Gautam Samant",
      "contact": "",
  },
  {
      "title": "Tensegrity structure",
      "description": "",
      "creator": "Shiv, Rahi and Siddharth",
      "contact": "",
  },
  {
      "title": "Magic strings 'The Chain Fountain Phenomenon'",
      "description": "",
      "creator": "Rupa Ghadi, Nidhi Ghadi, Tanmay, Srushti Bagewadi",
      "contact": "",
  },
  {
      "title": "Banana fibres",
      "description": "",
      "creator": "Gopikrishna and Vishwanath",
      "contact": "",
  },
  {
      "title": "3D constellation",
      "description": "",
      "creator": "Harshad, Shubham and Ashok",
      "contact": "",
  },
  {
      "title": "Demo of Newton's third law of motion",
      "description": "",
      "creator": "Ananya Ghadi, Tanmay, Shrusti Bagewadi and Ganesh Shinde",
      "contact": "",
  },
  {
      "title": "Laser maze",
      "description": "",
      "creator": "Shashanl",
      "contact": "",
  },
  {
      "title": "Laser show",
      "description": "",
      "creator": "Praveen Patil, Prathamesh Raikar, Shreyas Arjunwadkar, Atharva Chougule,  Arya Doddannavar, Kisan V,  Prathamesh P., Prem and Ritika",
      "contact": "",
  },
  {
      "title": "Live music team",
      "description": "",
      "creator": "Victor Fernandez, Ishaan Singh, Maruti",
      "contact": "",
  },
];
