module.exports = [
  {
      "title": "Electromagnetic Clock",
      "description": "Electromagnetic clock using relays, kuttypy and iron fillings.",
      "creator": "Sayan & Team",
      "contact": "https://yudocaa.in",
  },
  {
      "title": "Boat Navigation with Wifi",
      "description": "Remotely hand gesture controlled and navigated boat.",
      "creator": "Rohit & Team",
      "contact": "",
  },
  {
      "title": "Loom Bands workshop",
      "description": "",
      "creator": "Ovi & Eva",
      "contact": "",
  },
  {
      "title": "PYSSLA board",
      "description": "",
      "creator": "Ovi & Team",
      "contact": "",
  },
  {
      "title": "Experiments with Sun Printing",
      "description": "Use the cyanotype printing process to create prints using objects around us",
      "creator": "Arun & Team",
      "contact": "",
  },
  {
      "title": "Harmonic Oscillator",
      "description": "",
      "creator": "Jithin, Ishaan and Praveen",
      "contact": "",
  },
  {
      "title": "High voltage source and infusion pump",
      "description": "",
      "creator": "Praveen & Team",
      "contact": "",
  },
  {
      "title": "Plasma vortex",
      "description": "",
      "creator": "Prathmesh & Team",
      "contact": "",
  },
  {
      "title": "Health Vigilance",
      "description": "Built for patients and elders to raise an alert by monitoring heart rate using bangle JS",
      "creator": "Shabnam, Farhaan, Shekhar",
      "contact": "",
  },
  {
      "title": "Night vision driving improvement",
      "description": "Nigh vision driving improvement system using webcam and LCD screen to help drivers avoid bright light during driving",
      "creator": "Anant & Team",
      "contact": "",
  },
  {
      "title": "LLM Resume Search",
      "description": "Based on distilled bert which is a language transformer and GPT 4",
      "creator": "Shreyas",
      "contact": "",
  },
  {
      "title": "Triboelectric Generator",
      "description": "",
      "creator": "",
      "contact": "",
  },
  {
      "title": "Tensigrity Structure",
      "description": "Tension based structure",
      "creator": "Shiv & Team",
      "contact": "",
  },
  {
      "title": "Fractal Chair",
      "description": "Fractal based cushioning of chair based on body shape",
      "creator": "Ishaan and Goutam",
      "contact": "",
  },
];
